## it is not required to have language set as groovy, you may choose your project's lang.
## the `before_script` block installs required groovy
language: groovy

before_script:
  - TERM=dumb groovy --version
  - export GROOVY_VERSION=2.5.7
  - wget http://dl.bintray.com/groovy/maven/apache-groovy-binary-$GROOVY_VERSION.zip -O /tmp/groovy.zip
  - unzip /tmp/groovy.zip -d $PWD/.groovy
  - export PATH=$PWD/.groovy/groovy-$GROOVY_VERSION/bin:$PATH
  - echo "groovy installed ${GROOVY_VERSION}"

script:
  - TERM=dumb groovy --version
  - TERM=dumb groovy script.groovy some-arg

jdk:
  - oraclejdk8